name: CI

on:
  workflow_dispatch:
    inputs:
      Env:
        type: choice
        description: 'choose Environment' 
        options: 
        - dev
        - stg
        - prod
        required: true
        
# env:
#   TOTAL_VCPU: ${{ steps.count.outputs.total_vcpu}}
#   total_vcpu:  aws service-quotas get-service-quota --region ap-south-1 --service-code ec2 --quota-code L-1216C47A --query 'Quota.Value'
#   total_instance_limit: $total_vcpu/8
#   total_instance_runnng:  aws ec2 describe-instances --region ap-south-1 --output table --query 'Reservations[*].Instances[*].InstanceId' | grep i- | wc -l
#   request: $total_instance_running*.7
  
jobs:

  dev-deploy:
    runs-on: ubuntu-latest
    if:  ${{ github.event.inputs.Env == 'dev' }}
    steps:
      - uses: actions/checkout@v2
        
        
      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # change as needed
          
#       - name:  instances
#         run: |
#             aws service-quotas get-service-quota --region ap-south-1 --service-code ec2 --quota-code L-1216C47A --query 'Quota.Value'
#             aws ec2 describe-instances --region ap-south-1 --output table --query 'Reservations[*].Instances[*].InstanceId' | grep i- | wc -l
      
      - name: Retrieve Total vcpu count
        run: |
          echo "::set-output name=total_vcpu::$(aws service-quotas get-service-quota --region ap-south-1 --service-code ec2 --quota-code L-1216C47A --query 'Quota.Value')"
        id: count
      
      - name: view instances
        env: 
          TOTAL_VCPU: ${{ steps.count.outputs.total_vcpu }}
          number: 8
           
        run: | 
            date
            echo ${TOTAL_VCPU}
               total= $(echo TOTAL_INSTANCES: $(($TOTAL_VCPU/1)) | bc)
          #  echo ::set-env name=NEWNUM::$((TOTAL_VCPU+1.2))
           # echo "New Number is $NEWNUM"
             
     
          
